### ISSUE TITLE
数据源mysql5.7提示 Error 1067 (42000): Invalid default value for 'heartbeat'

### ISSUE THREAD

**Issue by yinweiliaojie08** [sunwenbo/smart-api#1]
在MySQL5.7中timestamp是不能设置默认null的，两种解决方法，第一种修改mysql的全局配置explicit_defaults_for_timestamp=on，第二种是修改代码中关于表结构的定义，app\smart\models\exec_machine.go中把;default:NULL去掉应该就可以了

**Comment by sunwenbo** [comment]
推荐使用mysql 8.0
